### ISSUE TITLE
Perfect! Simple and fest installed - but a little feature request, too

### ISSUE THREAD

**Issue by p-Enzi** [crealistiques/cre_pagetreewidth#1]
Thanks for this extension.
I am using long page title and long, speaking filenames.
typo3 developers have decided to go back to last centuries DOS 8.3 names.
They want to do the same bugs as Mirosoft: 
Since decades they have small dialog-boxes where you cannot read long names.

But your extension is a good step into another direction ;-))

So there is a little question:
Is it possible to enhance the dialog box for entering links in the 
editor, too? 
In v8.7 there now is a small left badly readable pagetree 
where in v7.6 and before there was a full window and a fully visible pagetree.

**Comment by crealistiques** [comment]
Thank you. I took a quick look for the link dialog window and found that one could at least improve the page and folder tree width by resizing the whole dialog window in breadthways. By making it smaller the tree area spreads to full width. This might be a solution for you. If anybody else seems to require a more flexible solution here I'll consider an additional option. Have a good time.

**Comment by p-Enzi** [comment]
Thank you for your very fast answere.
Yes, I found your "reverse responsive" workaround, too - but its time-consuming.
And in my opinion its not the thing responsive-design should work: 
Make a window smaller to give small columns more room ;-))

**Comment by crealistiques** [comment]
Yes you're right, I agree. Check out the new version which adds a new setting to user prefs. Thanks you!
