### ISSUE TITLE
Request: Please repair rtehtmlarea, too ;-)

### ISSUE THREAD

**Issue by p-Enzi** [crealistiques/cre_pagetreewidth#2]
Thank you for your fast enhancements to the ckEditors link/file-dialog.
I had to step back to rtehtmlarea in the newest typo3-version 8.x:
ckEditor is not able to cumulate/add more css-classes to an element 
by selecting additionals classes from the blockstyles-selectbox.

But now I see:
In rtehtmlarea v8.x the dialogwindow for links/files is even smaller than in ckEditor.
I know the rtehtmlare is obsolete, 
but: Do you see any chance to enhance this with your pagetreewidth-magic?

**Comment by crealistiques** [comment]
My gift for christmas just arived ;) rtehtmlrea is now supported, too! At least I hope so.
